### ISSUE TITLE
ENH: Add Retrieval Augmented Generation (RAG) to the process

### ISSUE THREAD

**Issue by com3dian** [MahdiFarnaghi/intelli_geo#1]
### Tasks
- [x] Create a vector database for QGIS documentation.
- [x] Create a vector database for few shots examples.
- [x] When the plugin is loaded, create those above two plugins if they do not exist.
- [x] Use the datasets to enrich the prompts with required information (a reference to the documentation and few shots).

### Who is responsible
Lu @com3dian
