### ISSUE TITLE
ENH: Generated model saving & loading

### ISSUE THREAD

**Issue by com3dian** [MahdiFarnaghi/intelli_geo#2]
### Tasks
- [x] Save the output as a `*.model3` file.
- [x] For now, we are creating a folder within the OS document folder named `QGIS_IntelliGEO`.
- [x] Model file should be named like `model_<datetime>_<convname>_<iterator>.model3`.
- [x] Load the file using a command in the model designer.

### Who is responsible
Lu @com3dian
